### ISSUE TITLE
✨자유주제 제안: TDD

### ISSUE THREAD

**Issue by reddevilmidzy** [jmxx219/CS-Study#64]
📌 제안 주제
TDD (test-driven development)

⛳️ 제안 이유

* 좋은 코드, 좋은 프로그램을 만들기 위해서 꼭 필요한 개념이라고 생각
* 실습은 못하더라도 개념을 확실하게 잡으면 좋을 듯 함

🌿 제안 내용

* 개발주기
* 개발방식 
* 일반 개발 과정과의 차이점

**Comment by jmxx219** [comment]
[TDD 정리](https://github.com/jmxx219/CS-Study/blob/main/ETC/TDD.md)
